apiVersion: v1
kind: Service
metadata:  
  name: my-nodeport-service
  namespace: f5
spec:
  selector:    
    app: frontend
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30999
    protocol: TCP